export const CAR_DATA = [
  [
    {
      id: 1,
      name: "VW Golf 6",
      price: "37",
      img: "images/cars-big/golf6.jpg",
      model: "Golf 6",
      mark: "Volkswagen",
      year: "2008",
      doors: "4/5",
      air: "Yes",
      transmission: "Manual",
      fuel: "Diesel",
    },
  ],
  [
    {
      id: 2,
      name: "Audi A1 S-Line",
      price: "45",
      img: "images/cars-big/audia1.jpg",
      model: "Audi",
      mark: "A1",
      year: "2012",
      doors: "4/5",
      air: "Yes",
      transmission: "Manual",
      fuel: "Gasoline",
    },
  ],
  [
    {
      id: 3,
      name: "Toyota Camry",
      price: "30",
      img: "images/cars-big/toyotacamry.jpg",
      model: "Camry",
      mark: "Toyota",
      year: "2006",
      doors: "4/5",
      air: "Yes",
      transmission: "Automatic",
      fuel: "Hybrid",
    },
  ],
  [
    {
      id: 4,
      name: "BMW 320 ModernLine",
      price: "35",
      img: "images/cars-big/bmw320.jpg",
      model: "320",
      mark: "BMW",
      year: "2012",
      doors: "4/5",
      air: "Yes",
      transmission: "Manual",
      fuel: "Diesel",
    },
  ],
  [
    {
      id: 5,
      name: "Mercedes-Benz GLK",
      price: "50",
      img: "images/cars-big/benz.jpg",
      model: "Benz GLK",
      mark: "Mercedes",
      year: "2006",
      doors: "4/5",
      air: "Yes",
      transmission: "Manual",
      fuel: "Diesel",
    },
  ],
  [
    {
      id: 6,
      name: "VW Passat CC",
      price: "25",
      img: "images/cars-big/passatcc.jpg",
      model: "Passat CC",
      mark: "Volkswagen",
      year: "2008",
      doors: "4/5",
      air: "Yes",
      transmission: "Automatic",
      fuel: "Gasoline",
    },
  ],
];
export const CAR_DATA2 = [
  [
    {
      id: 1,
      name: "VW Golf 6",
      price: "37",
      img: "images/cars-big/golf6-box.png",
      model: "Golf 6",
      mark: "Volkswagen",
      year: "2008",
      doors: "4/5",
      air: "Yes",
      transmission: "Manual",
      fuel: "Diesel",
    },
  ],
  [
    {
      id: 2,
      name: "Audi A1 S-Line",
      price: "45",
      img: "images/cars-big/audi-box.png",
      model: "Audi",
      mark: "A1",
      year: "2012",
      doors: "4/5",
      air: "Yes",
      transmission: "Manual",
      fuel: "Gasoline",
    },
  ],
  [
    {
      id: 3,
      name: "Toyota Camry",
      price: "30",
      img: "images/cars-big/toyota-box.png",
      model: "Camry",
      mark: "Toyota",
      year: "2006",
      doors: "4/5",
      air: "Yes",
      transmission: "Automatic",
      fuel: "Hybrid",
    },
  ],
  [
    {
      id: 4,
      name: "BMW 320 ModernLine",
      price: "35",
      img: "images/cars-big/bmw-box.png",
      model: "320",
      mark: "BMW",
      year: "2012",
      doors: "4/5",
      air: "Yes",
      transmission: "Manual",
      fuel: "Diesel",
    },
  ],
  [
    {
      id: 5,
      name: "Mercedes-Benz GLK",
      price: "50",
      img: "images/cars-big/benz-box.png",
      model: "Benz GLK",
      mark: "Mercedes",
      year: "2006",
      doors: "4/5",
      air: "Yes",
      transmission: "Manual",
      fuel: "Diesel",
    },
  ],
  [
    {
      id: 6,
      name: "VW Passat CC",
      price: "25",
      img: "images/cars-big/passat-box.png",
      model: "Passat CC",
      mark: "Volkswagen",
      year: "2008",
      doors: "4/5",
      air: "Yes",
      transmission: "Automatic",
      fuel: "Gasoline",
    },
  ],
];
